/**
 * Light and Dark themes for testing-twigs package
 * Dark theme is generated by inverting/darkening the default light theme colors
 */

import { defaultTheme, TwigsTheme, DeepPartial } from 'testing-twigs';

// Light theme - using the default theme colors
export const lightTheme: DeepPartial<TwigsTheme> = {
  colors: {
    // Keep the default light theme colors
    ...defaultTheme.colors,
  },
};

// Dark theme - generated equivalent dark colors
export const darkTheme: DeepPartial<TwigsTheme> = {
  colors: {
    primary: '#4AADB6',
    secondary: '#B8BCC4',

    // Accent colors - inverted scale (darker at low numbers in dark mode)
    accent50: '#1A1A2E',
    accent100: '#252542',
    accent200: '#2E2E52',
    accent300: '#3D3D6B',
    accent400: '#5050A0',
    accent500: '#7158F5',
    accent600: '#8F7AF7',
    accent700: '#A896F9',
    accent800: '#C4B8FB',
    accent900: '#E0DAFD',

    // Primary colors - inverted for dark mode
    primary50: '#0D2628',
    primary100: '#153D40',
    primary200: '#1E5559',
    primary300: '#276D73',
    primary400: '#30858C',
    primary500: '#3A9DA5',
    primary600: '#59B1B8',
    primary700: '#79C4CB',
    primary800: '#9AD7DD',
    primary900: '#BAEAEF',

    // Warning colors - adjusted for dark backgrounds
    warning50: '#2E2510',
    warning100: '#3D3015',
    warning200: '#5C4A1A',
    warning300: '#7A6320',
    warning400: '#997D26',
    warning500: '#B8972C',
    warning600: '#D7B245',
    warning700: '#E8C85E',
    warning800: '#F5DD78',
    warning900: '#FFF291',

    // Highlight colors
    highlight50: '#2E2E0D',
    highlight100: '#3D3D15',
    highlight200: '#5C5C1A',
    highlight300: '#7A7A20',
    highlight400: '#999926',
    highlight500: '#B8B82C',
    highlight600: '#D7D745',
    highlight700: '#E8E85E',
    highlight800: '#F5F578',
    highlight900: '#FFFF91',

    // Positive/success colors
    positive50: '#0D1F0A',
    positive100: '#152D10',
    positive200: '#1E3D16',
    positive300: '#274D1D',
    positive400: '#305D24',
    positive500: '#3A6D2B',
    positive600: '#4D8A38',
    positive700: '#60A745',
    positive800: '#73C452',
    positive900: '#87E160',

    // Secondary colors - adjusted for dark mode
    secondary50: '#1A1C1F',
    secondary100: '#252830',
    secondary200: '#303540',
    secondary300: '#3D4450',
    secondary400: '#4B5563',
    secondary500: '#5B6778',
    secondary600: '#6C798D',
    secondary700: '#8693A6',
    secondary800: '#A1ACBC',
    secondary900: '#BDC5D2',

    // Negative/error colors
    negative50: '#2E1510',
    negative100: '#3D1D15',
    negative200: '#5C261A',
    negative300: '#7A3020',
    negative400: '#993A26',
    negative500: '#B8442C',
    negative600: '#D75745',
    negative700: '#E86A5E',
    negative800: '#F58078',
    negative900: '#FF9691',

    // Neutral colors - inverted scale for dark mode
    neutral50: '#111111',
    neutral100: '#1A1A1A',
    neutral200: '#2D2D2D',
    neutral300: '#404040',
    neutral400: '#525252',
    neutral500: '#6B6B6B',
    neutral600: '#858585',
    neutral700: '#A0A0A0',
    neutral800: '#BABABA',
    neutral900: '#F5F5F5',

    // Black colors - remain same (opacity variations)
    black50: '#FFFFFF0A',
    black100: '#FFFFFF14',
    black200: '#FFFFFF1A',
    black300: '#FFFFFF26',
    black400: '#FFFFFF33',
    black500: '#FFFFFF4D',
    black600: '#FFFFFF80',
    black700: '#FFFFFFB2',
    black800: '#FFFFFFCC',
    black900: '#FFFFFF',

    // White colors - INVERTED for dark mode (white900 becomes dark background)
    white50: '#0000000D',
    white100: '#00000014',
    white200: '#0000001A',
    white300: '#00000026',
    white400: '#00000033',
    white500: '#0000004D',
    white600: '#00000080',
    white700: '#000000B2',
    white800: '#1A1A1A',
    white900: '#121212', // Dark background for BottomSheet, cards, etc.
  },
};

// Background colors for the app container
export const appBackgroundColors = {
  light: '#FFFFFF',
  dark: '#0F0F0F',
};

// Surface colors for cards and elevated elements
export const surfaceColors = {
  light: '#FFFFFF',
  dark: '#1A1A1A',
};

// Border colors
export const borderColors = {
  light: '#E2E2E2',
  dark: '#2D2D2D',
};
